language: ruby
bundler_args: --without development
script:
  - RAILS_ENV=test bundle exec rake spec
rvm:
  - 2.0.0
  - 1.9.3
matrix:
  allow_failures:
    - rvm: 2.0.0
notifications:
  email: false
branches:
  except:
    - release
